### PR TITLE
Prevent crash when network is down

### LINKED ISSUE #7: Cannot convert argument to string: Error Domain=RCTErrorDomain Code=0"Invalid type in JSON write (NSURLError)"
```
2016-04-08 18:35:54.606 [error][tid:com.facebook.React.JavaScript][RCTJSCExecutor.m:428] Cannot convert argument to string: Error Domain=RCTErrorDomain Code=0 "Invalid type in JSON write (NSURLError)" UserInfo={NSLocalizedDescription=Invalid type in JSON write (NSURLError)}
2016-04-08 18:35:54.633 [fatal][tid:com.facebook.React.JavaScript] Invalid type in JSON write (NSURLError)
```

To reproduce: 

* Install this library into a React Native project and set up the SDK following [these instructions](https://dev.branch.io/getting-started/sdk-integration-guide/guide/react/) 
  * Specifically add this line to `didFinishLaunchingWithOptions`: `[RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];`
* Simulate no network connection (turn on Airplane Mode or wifi if testing in Simulator)
* Call `branch.getFirstReferringParams()` or `branch.getLatestReferringParams()`

When I comment out the `initSessionWithLaunchOptions` line, the app doesn't crash. So, it appears that the `initSessionWithLaunchOptions` method is receiving a something other than a string when it's expecting a string. More importantly though, I still get deeplink data even with `initSessionWithLaunchOptions` commented out, so I'm wondering why this method is even necessary?

### PR DESCRIPTION
**Pull request by magus**
close #7 

Red screen error when notification object contains an error object from a failed request. I was able to 100% reproduce the issue by using LittleSnitch to block outgoing network traffic for my app on the simulator.

The was causing a crash of the app in production with an error message that didn’t really give much detail. Fortunately I was able to get a user who had the issue to tell me it happened when his network connection was spotty. Used LittleSnitch and put a breakpoint in the `RCTJSExecutor.m` `_executeJSCall` method. Continued until I saw the log of the error and then backtracked to the event previous and it was the init call for RNBranch. Added in the checks in the PR and things are good now.

---
This change is [Reviewable](https://reviewable.io/reviews/branchmetrics/react-native-deep-linking-sdk/8)

### CODE REVIEW

File: RNBranch/RNBranch/RNBranch.m [hunk 1]
```diff
@@ -52,7 +52,17 @@ - (void) dealloc {
...
 
 - (void) onInitSessionFinished:(NSNotification*) notification {
-  [self.bridge.eventDispatcher sendDeviceEventWithName:@"RNBranch.initSessionFinished" body:[notification object]];
+    id notificationObject = notification.object;
+
+    // If there is an error, send back along the localized description string
+    // Raw object may contain objects which cannot be converted to JS objects
+    if (notificationObject[@"error"] != [NSNull null]) {
+        NSString* errorDescription = [notificationObject[@"error"] localizedDescription];
+        NSLog(@"%@", errorDescription);
```
Comment (rt2zz) [inline RNBranch/RNBranch/RNBranch.m]: Remove NSLog

**Comment by rt2zz** [comment]
Awesome! Just one nit about the NSLog and this should be good to merge.

Also thanks for the debugging detail, it is much appreciated.

**Comment by magus** [comment]
Removed the log statement

**Comment by rt2zz** [comment]
@magus we are moving the repo to https://github.com/BranchMetrics/react-native-branch which your commit has been applied to. We will be deprecating this repo in the near future.

**note** the new repo changes the package name to `react-native-branch` so your gradle and xcode linking will have to be updated accordingly.

**Comment by rt2zz** [comment]
👍  @aaustin this PR has been tested and is verified working. I would recommend merging for the short term benefits of current users.

I will publish migration instructions to the new repo tomorrow.

**Comment by aaustin** [comment]
Boom :+1:

**Comment by livioso** [comment]
Cool. Any plans to release this to npm (as version 0.8.1) any time soon?

**Comment by rt2zz** [comment]
@livioso we will be cutting a new release next week. Will uodate here with more info when it is available.
